### ISSUE TITLE
Vue.js bug

### ISSUE THREAD

**Issue by cliffckerr** [sciris/sciris-js#4]
Doesn't work with Vue 3.0, only works with 2.6:
```
sciris-js.js:16519 Uncaught TypeError: window.Vue.use is not a function
```
